### ISSUE TITLE
Running snoopy_auth against latest sqlalchemy produces an error

### ISSUE THREAD

**Issue by maximcherny** [sensepost/snoopy-ng#10]
```python
>>> import sqlalchemy
>>> sqlalchemy.__version__ 
'0.9.7'
```

```bash
snoopy_auth -l
[+] Available drone accounts:
Traceback (most recent call last):
  File "/usr/bin/snoopy_auth", line 103, in <module>
    drones = auth_.manage_drone_account("foo", "list")
  File "/usr/bin/snoopy_auth", line 29, in manage_drone_account
    self.db.create(self.drone_tbl_def )
  File "<string>", line 2, in create
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/deprecations.py", line 106, in warned
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/interfaces.py", line 859, in create
    raise NotImplementedError()
NotImplementedError
```

This works correctly against 0.7.8.

Perhaps, a specific known working version needs to be requested by the installation script.

What is the version being developed against?

**Comment by aiddenkeli** [comment]
Uh this maybe a stupid question but where exactly is snoopy_auth located?

**Comment by JosephGregg** [comment]
From install.sh:
ln -s `pwd`/includes/auth_handler.py /usr/bin/snoopy_auth

so you can find it snoopy-ng/includes/auth_handler.py

**Comment by dustyb** [comment]
temp workaround 
easy_install "SQLAlchemy==0.7.8"

**Comment by ElkanRoelen** [comment]
@dustyb 
This fixed it for me! (specially created an account to tell you that.. :D)
OS: Ubuntu gnome 14.04

**Comment by dustyb** [comment]
@ElkanRoelen awesome. Glad so see I wasn't the only one with the issue.
