### ISSUE TITLE
Maltego - Windows

### ISSUE THREAD

**Issue by mstekker** [sensepost/snoopy-ng#25]
Hi,

I am testing Snoopy with Maltego. Snoopy runs fine, but when I copy snoopy.db to my Windows machine and want to use Maltego for analysing I get the following error:

-> fetchDrones: "The directory is invalid". 

dbpath is: sqlite:///c:\snoopy\snoopy.db 
(changed this in the config)

Importing the .mtz etc into Maltego went without any errors.

Any ideas?

Thx in advance.

Mart

**Comment by glennzw** [comment]
Did the above advice help? I've never tried on Windows.
