### ISSUE TITLE
Error Wigle

### ISSUE THREAD

**Issue by Akumuryu** [sensepost/snoopy-ng#28]
Anyone see this error regarding fetchSSIDLocationsLive transform. When selecting the SSID and selecting the fetchSSIDLocationsLive im getting " Error: Please supply the wigle credentials in the property view on the right" 

can't see anything that would allow placing the creds, even when i was looking a the script.

**Comment by glennzw** [comment]
I need to update the fetchSSIDLocation_live transform to allow creds in the transform. For now, create a file in the transform directory called `wigle_creds.txt` and populate it with:

`<wigle_user>:<wigle_pass>:<email>:[optional_proxy]`

e.g.:

`glenn:amazingPassword:glenn@sensepost.com:`

Note the final colon even if not using a proxy.

Alternatively, use the wigle plugin on the command line. This will do lookups as new SSIDs are observed, and can be browsed via the fetchSSIDLocations transform:

`wigle:username=glenn,password=amazingPassword,email=glenn@sensepost.com`
