### ISSUE TITLE
RogueAP network crashing

### ISSUE THREAD

**Issue by Wald01991** [sensepost/snoopy-ng#29]
Running Raspberry Pi Kali and Alfa Awus036h. I can run rogueAP, with run_dhcp and local_nat, and connect if I have my eth0 interface down but, then my rogueAP has no internet access. If I have eth0 up when I start Snoopy and I connect to the rogue access point the network goes down and my mon0 interface disappears. If I start Snoopy with eth0 down I can connect to the access point without internet access but, the moment I bring up eth0 it shuts down the network and gets rid of mon0.

**Comment by Wald01991** [comment]
Turns out that because I was accessing my Pi through SSH I wasn't receiving all system messages and didn't see the message telling me my Alfa was being disconnected due to over current protection. Putting "max_usb_current=1" in the boot file solved my issue. Everything is working great now.

**Comment by glennzw** [comment]
The Pi does have power issues. My primary platform is a BeagleBoneBlack with a powered USB hub + 3A adapter. Glad you fixed it.
