### ISSUE TITLE
Run Fail

### ISSUE THREAD

**Issue by aiddenkeli** [sensepost/snoopy-ng#3]
Running on fresh install of Kali 1.0.7

When running:

./snoopy.py --drone mac -l test -v -m wifi:mon0=True -m sysinfo -m heartbeat

This is the output:

Traceback (most recent call last):
  File "./snoopy.py", line 428, in <module>
    main()
  File "./snoopy.py", line 353, in main
    plugins = common.get_plugins()
  File "/root/snoopy-ng/includes/common.py", line 24, in get_plugins
    m = __import__(plug, fromlist="Snoop").Snoop
  File "/root/snoopy-ng/plugins/gpsd.py", line 15, in <module>
    from gps import *#gps, WATCH_ENABLE
ImportError: No module named gps
root@kali:~/snoopy-ng#

**Comment by geoffwhite247** [comment]
I'm running snoopy-ng on an osboxes image of Kali 1.1.0,and get the same error message when I try to run wifi plugin:

root@osboxes:~/snoopy-ng# python snoopy.py -vv -d Geoff home31oct -m wifi:iface=wlan0

returns:

Traceback (most recent call last):
  File "snoopy.py", line 428, in <module>
    main()
  File "snoopy.py", line 353, in main
    plugins = common.get_plugins()
  File "/root/snoopy-ng/includes/common.py", line 24, in get_plugins
    m = **import**(plug, fromlist="Snoop").Snoop
  File "/root/snoopy-ng/plugins/gpsd.py", line 15, in <module>
    from gps import *#gps, WATCH_ENABLE
ImportError: No module named gps

I also had an ntpdate error when I first installed (unable to find package), but thought I'd sorted that by changing my sources list...

Any hints gratefully received!

**Comment by geoffwhite247** [comment]
Hmmmm, I found this in the code from when I originally installed snoopy-ng, could it  have something to do with it?

W: A error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://security.kali.org sana/updates Release: The following signatures were invalid: BADSIG ED444FF07D8D0BF6 Kali Linux Repository devel@kali.org

W: Failed to fetch http://security.kali.org/kali-security/dists/sana/updates/Release  

W: Some index files failed to download. They have been ignored, or old ones used instead.
