### ISSUE TITLE
Not scanning across wifi channels

### ISSUE THREAD

**Issue by jimbonet** [sensepost/snoopy-ng#30]
I am running 1.09 kali image on raspberry pi with Alfa awus051nh (dualband) and have found that I only appear to detect APs and clients on one channel. when i run kismet or wifi analyser on another device I detect lots more APs/clients in the same location.
I have tried wifi:mon=True and false and also tried placing alfa into monitor mode before running snoopy but still no joy.

It seems like snoopy locks on one channel when it runs rather than hopping. I have ran airodump-ng on same pi and it scans all the channels so do think its a driver issue.

Any thoughts?

note: I had to comment out mitmproxy in install.sh and remove the mitmproxy.py to compile without errors

**Comment by 7109node** [comment]
Esvanoe is correct.  The easiest way I have found is to start airodump-ng as a startup service in init.d with the appropriate headers.  Then have the snoopy call in rc.local as normal using iface=mon0.  This works since you already specified mon0 during the airodump startup script.

I use this setup on my pi B+ and it works flawlessly.

**Comment by th36r1m** [comment]
This may sound silly, but make sure you aren't connected to a wireless network on your 'wlan' interface when you put the card into monitor mode. I'm running 1.0.9 using my alfa card using 'wifi:mon=True' with no problem, and I don't start anything extra at start up. If you are connected, then your card will only scan that particular channel.

**Comment by glennzw** [comment]
Keep in mind 'mon=True' will just run 'airmon-ng', note the first available adapter, and run 'airmon-ng start wlanXX'. Snoopy then listens on whatever monitor interface is returned. You could run the airmon-ng commands yourself, then run with 'iface=monX'.

You're right on the channel hopping. I was trying to figure out an elegant way to hop, but backgrounding airodump is the solution for now. So, in summary:

`snoopy -l home -d myDrone -m wifi:mon=True -v & airodump-ng mon0`
  or
`airmon-ng start wlan0 && airmon-ng check kill && snoopy -l home -d myDrone -m wifi:iface=mon0 -v & airodump-ng mon0`

I might add an option to the wifi plugin to background airodump for us.
