### ISSUE TITLE
KeyError: 'mtk' in Maltego

### ISSUE THREAD

**Issue by stevenhorner** [sensepost/snoopy-ng#36]
When I try to run any transforms in Maltego I get a python error.

The full Debug output is:

File "fetchDrones.py", line 13, in <module>
from transformCommon import *
File "/root/snoopy-ng/transforms/transformCommon.py", line 36, in <module>
mtk = metadata.tables['mtk']
KeyError: 'mtk'

I am actually running this from a Kali-linux Live CD just to test it before doing a full install. Data is being written into the SQLite database I can see ssids in 'wifi_client_ssids' and data in a couple of other tables.

What is this 'mtk' table it doesn't exist in my SQLite DB. I can see that the line that follow 37 & 38 specify 'users' and 'sessions' they don't exist in my DB either or is this trying to create them.

Any help appreciated, it could be because I'm running on a live CD. I was kind of surprised it installed and appears to run fine except for the Maltego transforms.

**Comment by mexmustermann** [comment]
You have to run snoopy with the server plugin again. "snoopy -v -m server" 
Then the missing mtk entry  will be written in the snoopy.db.
for me it works ;)

**Comment by stevenhorner** [comment]
Thanks that worked. 

I had followed the quick instructions to save the data locally and then tried to use Maltego to view it. Maybe the quick instructions should mention you need to run "snoopy -v -m server" at least once for Maltego to open it (unless I missed that part).

**Comment by mexmustermann** [comment]
That just happens when you collect data with an "old" version of snoopy (old db structure) and then try to work with this old database in the newest commit where the new "mtk" entry was added. so its only an one time migragtion problem.
