### ISSUE TITLE
Plugin to allow probe request capture

### ISSUE THREAD

**Issue by maximcherny** [sensepost/snoopy-ng#4]
Hi,

The original version of Snoopy (circa 2012) facilitated the ability to store the attributes of probe requests. The ng version only seems to capture aggregates via num_probes.

Is this a deliberate design decision?

Cheers

**Comment by glennzw** [comment]
Regarding data replication; I wrote the code because I couldn't find any standard ways to handle it, but it isn't the most elegant solution. I'm hoping to have a ZeroMQ version built at some point.
