### ISSUE TITLE
shadow keys?

### ISSUE THREAD

**Issue by 7109node** [sensepost/snoopy-ng#49]
I just updated to Maltego Chlorine and now whenever I try to run a transform on the base of operations it is asking me for a shadow key.  I'm obviously missing something basic. Any guidance on this?

**Comment by esvanoe** [comment]
That sounds like when you are trying to run a transform designed for remote data instead of local transform on local data. I remember playing with the shadow key stuff a while back for remotely stored data, it was like the secret password to access the SQL database or something.

**Comment by 7109node** [comment]
Yeah...I'm an idiot carry on. Chlorine brought in the new snoopy transforms which link to the shadow site.

**Comment by glennzw** [comment]
Correct - the transforms can be identified with the SLY at the beginning:
SLYfetchDrones - TDS for shadowlightly.com
fetchDrones - local transform
