### ISSUE TITLE
MTK error Not related to server

### ISSUE THREAD

**Issue by edlovesiraq** [sensepost/snoopy-ng#50]
Full error.
Traceback (most recent call last):
  File "fetchDrones.py", line 13, in <module>
    from transformCommon import *
  File "/root/snoopy-ng/transforms/transformCommon.py", line 36, in <module>
    mtk = metadata.tables['mtk']
KeyError: 'mtk'

-I've tried running it -m server, and many variations with -m. It runs fine, the sqlite db is there and can be viewed with a sqlbrowser, but I still get that error. 
-made sure the date encompassed the data pluss a day on either side.
-clean install of kali 1.1 (could that be the issue? it's running maltego tungston kali edition: I'll try to install carbon manually and see if that works but I don't see MTK as a field in the db so i think snoopy is failing to creat the right fields to be ingested? )
Wouldn't right if I hadn't tried everything I could think of.
Ed

**Comment by 7109node** [comment]
I had the same issue, I rolled back to a previous snoopy I had on my linode and everything is working fine again.  I'm not sure what the issue was.

**Comment by edlovesiraq** [comment]
Fresh instal, then I started with the server; then a local transform and now i'm in buisness. Now I'm writing Bobzilla and asking him to unblock my account ;)... This software is ABSOLUTELY BRILLIANT!! using it to teach wireless security tomorrow.

**Comment by glennzw** [comment]
Thanks for noticing this bug. I've just pushed a fix.
