### ISSUE TITLE
snoopy-ng git does not ship with or create a instance of snoopy.db

### ISSUE THREAD

**Issue by thesle3p** [sensepost/snoopy-ng#53]
While the installer does a great job of installing dependencies and even telling snoopy-ng where to look for snoopy.db snoopy-ng does not come with a empty instance of snoopy.db nor does the installer create one. causing the following issues when snoopy is run with out arguments or with -iii  :
Traceback (most recent call last):
  File "/usr/bin/snoopy", line 428, in <module>
    main()
  File "/usr/bin/snoopy", line 353, in main
    plugins = common.get_plugins()
  File ""<basedir>/snoopy-ng/includes/common.py", line 24, in get_plugins
    m = __import__(plug, fromlist="Snoop").Snoop
  File ""<basedir>/snoopy-ng/plugins/server.py", line 17, in <module>
    from includes import webserver
  File "<basedir>snoopy-ng/includes/webserver.py", line 27, in <module>
    auth_ = auth()
  File ""<basedir>snoopy-ng/includes/auth_handler.py", line 46, in __init__
    self.db.create(drone_tbl_def)
  File "<string>", line 2, in create
  File "/usr/lib/python2.7/site-packages/sqlalchemy/util/deprecations.py", line 106, in warned
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/interfaces.py", line 924, in create
    raise NotImplementedError()
NotImplementedError
 
The solution is to add either a empty snoopy.db file to the git repo or have the installer create one and populate it with the tables it needs. I guess having a empty snoopy.db in the git repo would be a easier fix then adding logic to do it to the installer script.

**Comment by maximcherny** [comment]
What version of sqlalchemy are you running? I had similar issues with the more recent ones, but not with 0.7.8.

**Comment by thesle3p** [comment]
0.9.9-2 on Manjaro.

**Comment by maximcherny** [comment]
Downgrading to 0.7.8 should get you going. Latest Kali for instance still comes with that.

**Comment by thesle3p** [comment]
Thanks it worked. Weird that newer sqlalchemy broke snoopy-ng.

**Comment by rookdave** [comment]
I was running into this issue and figured out what was wrong. The install assumes I'm installing to /root/snoopy-ng rather than where I had, /etc/snoopy-ng. It should be storing the path it was run from and then using that going forward (or update the documentation, etc).

**Comment by glennzw** [comment]
@rookdave I don't think there are any absolute path references. The ```install.sh``` file creates shortcuts from the current directory. Where did you run into this?

https://github.com/sensepost/snoopy-ng/blob/master/install.sh#L90

**Comment by thesle3p** [comment]
It looks for it here https://github.com/sensepost/snoopy-ng/blob/master/includes/auth_handler.py#L164

**Comment by glennzw** [comment]
@rookdave @thesle3p Ah, thanks for pointing that out! I've pushed a fix in https://github.com/sensepost/snoopy-ng/commit/acc6af8c19d2ef34b57d6b23d514ae9f1037d47f
