### ISSUE TITLE
Scapy exception whilst sniffing. Will back off for 5 seconds

### ISSUE THREAD

**Issue by dustyb** [sensepost/snoopy-ng#55]
So for some reason I keep getting this Scapy exception on a beagalbone i'm installing.. When I start snoopy in drone mode I see the below. 

sudo snoopy -v -m wifi:iface=mon0,mon=False -m sysinfo -m heartbeat -d myDrone -l basement

[+] Starting Snoopy with plugins: wifi, sysinfo, heartbeat
[+] Capturing local only. Saving to 'sqlite:///snoopy.db'
[+] Waiting for plugin 'wifi' to indicate it's ready
[+] Starting sniffing on interface 'mon0'
=> [!!] Scapy exception whilst sniffing. Will back off for 5 seconds, and try restart 'plugins.wifi' plugin
=> [!!] __init__() got an unexpected keyword argument 'stopperTimeout'
[+] Plugin 'wifi' has indicated it's ready.
[+] Waiting for plugin 'sysinfo' to indicate it's ready
[+] Plugin 'sysinfo' has indicated it's ready.
[+] Waiting for plugin 'heartbeat' to indicate it's ready
[+] Plugin sysinfo will check device status every 1800 seconds.
[+] Plugin 'heartbeat' has indicated it's ready.
[+] Done loading plugins, running...
[+] Plugin heartbeat had a beat ❤ 
[+] Starting sniffing on interface 'mon0'
=> [!!] Scapy exception whilst sniffing. Will back off for 5 seconds, and try restart 'plugins.wifi' plugin
=> [!!] __init__() got an unexpected keyword argument 'stopperTimeout'
[+] Starting sniffing on interface 'mon0'
=> [!!] Scapy exception whilst sniffing. Will back off for 5 seconds, and try restart 'plugins.wifi' plugin
=> [!!] __init__() got an unexpected keyword argument 'stopperTimeout'
[+] Plugin sysinfo generated new data.
[+] Starting sniffing on interface 'mon0'
=> [!!] Scapy exception whilst sniffing. Will back off for 5 seconds, and try restart 'plugins.wifi' plugin
=> [!!] __init__() got an unexpected keyword argument 'stopperTimeout'
=> [!!] Restarting module '/home/debian/snoopy-ng/plugins/wifi.pyc' after 5 failed attempts
[+] Starting sniffing on interface 'mon0'
   [!!] Scapy exception whilst sniffing. Will back off for 5 seconds, and try restart 'plugins.wifi' plugin
   [!!] __init__() got an unexpected keyword argument 'stopperTimeout'
   [!!] Restarting module '/home/debian/snoopy-ng/plugins/wifi.pyc' after 5 failed attempts
Ctrl+C! Saving data and shutting down...

Any advice would be appreciated.

**Comment by maximcherny** [comment]
Are you sure you are running a patched version of scapy that is shipped with snoopy-ng? The stopperTimeout parameter is a non-native addition to the sniff() function of scapy.

**Comment by dustyb** [comment]
So I imaged a new SD for the beagal from the vanilla beagal-bone img. 

I then installed the snoopy-ng packages/requirements. I first noticed this exception right after the first run of snoopy, with the patch installed(no extra scapy stuff). 

[SOLUTION]: I removed scapy from the machine (sudo apt-get remove python-scapy) and just ran the scapy-patch file in the snoopy-ng bundle again, which gives me Scapy2.1.0 (sudo pip install ./setup/scapy-latest-snoopy_patch.tar.gz). This solved the problem. 

sudo apt-get remove python-scapy
cd snoopy-ng/
sudo pip install ./setup/scapy-latest-snoopy_patch.tar.gz

**Comment by ashtheman** [comment]
Hi, guys has this issue been resolved ? i am still stuck in this after trying all the suggestions even after running the patch? are there steps to follow?

**Comment by gunwi** [comment]
@dustyb:
Your "solution" has on the other hand, that
dhcpig fern-wifi-cracker ghost-phisher inguma kali-linux-full w3af w3af-console wifitap wol-e 
will be also removed.
Trying to reinstall one of the above will reinstall the "wrong" scapy - so that is no solution.

**Comment by Hacksawfred3232** [comment]
@gunwi However on the otherhand, there is a way of blocking the automatic installing of the wrong scapy. Look at this:http://askubuntu.com/questions/24609/blacklisting-packages-from-installing
If you install the package then stop updates for scapy, it will attempt to update but will fail as its been marked not to update. at least thats what i see.

**Comment by dustyb** [comment]
@gunwi I did not install on Kali. So the solution does work for me.

**Comment by NoobieDog** [comment]
NOTE: on Kali Nethunter 3 i had this issue (also on Kali 2(randomly))

I replaced the patched files over the scapy already installed. rebooted, worked like a charm, just need to remember that when i update/upgrade to replace it just incase
